export const Constants = {
    accessDenied: 'Access Denied',
    accessDeniedMessage: 'You do not have permission to view this page. Please return to the previous page or visit the homepage.',
    accessDeniedGoBackMessage: 'Go Back',
    welcomeMessage: 'Welcome to UpKeepz',
    welcomeSub: 'Here\'s your maintenance overview for today',
    pendingMessage: 'Pending Requests',
    awaitingMessage: 'Awaiting Approval',
    approvedMessage: 'Approved Requests',
    readyMessage: 'Ready for Service',
    SUCCESS: 'Success',
    errorProfileFetch: 'Error fetching the profile details: ',
    errorProfileUpdate: 'Error updating the profile: ',
    errorPasswordUpdate: 'Error updating the password: ',
    errorDeletingProfile: 'Error deleting profile: ',
    errorResidentDetailFetch: 'Error fetching resident details: ',
    errorOfficerDetailFetch: 'Error fetching officer details: ',
    errorAddOfficer: 'Error adding officer to the system: ',
    errorDeleteResident: 'Error deleting resident: ',
    errorDeleteOfficer: 'Error deleting officer: ',
    errorFetchingFeedbacks: 'Error fetching feedbacks: ',
    errorAddingFeedbacks: 'Error adding feedback: ',
    errorFetchingInvoices: 'Error fetching invoices: ',
    errorAddingInvoice: 'Error adding invoice: ',
    errorSearchingInvoice: 'Error searching invoices: ',
    errorFetchingNotices: 'Error fetching notices: ',
    errorSearchingNotices: 'Error searching notices: ',
    errorAddingNotices: 'Error adding notice: ',
    errorSearchingRequests: 'Error in searching requests: ',
    errorFetchingTimeSlots: 'Error occured while fetching the time slots: ',
    errorAddingRequest: 'Error adding request: ',
    errorFetchingRequestOfResident: 'Error fetching the requests of resident: ',
    errorDeleteRequest: 'Error in deleting service request: ',
    errorFetchingAllRequests: 'Error fetching all requests: ',
    errorReschedulingRequests: 'Error rescheduling request: ',
    
}